site:
  title: Building the OpenShift AI Foundation - The Operator Ecosystem
  start_page: rhoai3-operators::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
